"use client";

import { useEffect, useState } from "react";

type Beach = { id: string; name: string; area: string; wave: string; period: string; wind: string; score: number; color: string; coords: [number, number] };
const beaches: Beach[] = [
  { id: "stella", name: "Stella Maris", area: "Litoral norte · Salvador", wave: "1,2 m", period: "10 s", wind: "SE · 12 km/h", score: 86, color: "#74d7c9", coords: [-12.93, -38.32] },
  { id: "flamengo", name: "Praia do Flamengo", area: "Litoral norte · Salvador", wave: "1,0 m", period: "9 s", wind: "SE · 15 km/h", score: 78, color: "#f4bf67", coords: [-12.91, -38.31] },
  { id: "itapua", name: "Itapuã", area: "Orla de Salvador", wave: "0,8 m", period: "8 s", wind: "E · 17 km/h", score: 71, color: "#7aa7ff", coords: [-12.95, -38.36] },
  { id: "jaguaribe", name: "Jaguaribe", area: "Orla de Salvador", wave: "0,7 m", period: "8 s", wind: "E · 18 km/h", score: 68, color: "#ee8a78", coords: [-12.96, -38.38] },
];
const tabs = ["Agora", "Maré", "Ondas", "Vento"];

export default function Home() {
  const [activeBeach, setActiveBeach] = useState(beaches[0]);
  const [activeTab, setActiveTab] = useState("Agora");
  const [saved, setSaved] = useState(false);
  const [locationOpen, setLocationOpen] = useState(false);
  const [liveWind, setLiveWind] = useState<number | null>(null);
  const [apiState, setApiState] = useState("conectando");
  useEffect(() => {
    const [latitude, longitude] = activeBeach.coords;
    fetch(`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=wind_speed_10m,wind_direction_10m,temperature_2m&timezone=America%2FBahia`)
      .then((r) => r.json()).then((data) => { if (data.current?.wind_speed_10m) setLiveWind(Math.round(data.current.wind_speed_10m)); setApiState("atualizado"); }).catch(() => setApiState("última leitura"));
  }, [activeBeach]);
  const chart = activeTab === "Maré" ? "M0 79 C45 78 59 28 105 36 S165 98 215 66 S275 16 328 28 S398 88 452 58 S514 18 576 31" : activeTab === "Vento" ? "M0 67 C55 55 74 62 116 41 S188 38 224 55 S295 37 341 47 S422 28 458 43 S530 51 576 25" : "M0 69 C46 67 61 48 107 51 S168 75 215 43 S272 22 322 38 S380 66 424 42 S499 21 576 32";
  return <main className="ondai-shell">
    <header className="topbar"><a className="brand" href="#inicio"><span className="brand-mark">◜</span>ondai</a><nav><a className="active" href="#inicio">Início</a><a href="#mapa">Mapa</a><a href="#relatos">Relatos</a><a href="#perfil">Perfil</a></nav><div className="top-actions"><button className="location-button" onClick={() => setLocationOpen(!locationOpen)}>⌖ Salvador　⌄</button><button className="avatar-button">R</button></div>{locationOpen && <div className="location-popover"><b>Onde você surfa?</b><span>Salvador selecionado</span><button onClick={() => setLocationOpen(false)}>Usar minha localização</button></div>}</header>
    <section className="hero" id="inicio"><div className="hero-copy"><div className="eyebrow"><i /> CONDIÇÕES AO VIVO · SALVADOR</div><h1>Leia o mar.<br /><em>Escolha sua onda.</em></h1><p>Uma visão simples e honesta das praias para você decidir onde cair hoje.</p><div className="hero-actions"><button className="primary-button" onClick={() => document.getElementById("mapa")?.scrollIntoView({ behavior: "smooth" })}>Explorar praias <span>↗</span></button><button className="text-button" onClick={() => setSaved(!saved)}>{saved ? "Praia salva" : "Como funciona"}　↓</button></div></div><div className="hero-tide"><div className="moon-large">◔</div><div className="orbit one" /><div className="orbit two" /><div className="tide-label"><span>MARÉ AGORA</span><strong>Vazante</strong><small>↓ 0,8 m　<em>em 1h 24min</em></small></div></div></section>
    <section className="recommendation"><div className="section-heading"><div><span className="kicker">PARA VOCÊ · NÍVEL INTERMEDIÁRIO</span><h2>Melhor opção agora</h2></div><button className="view-all" onClick={() => document.getElementById("mapa")?.scrollIntoView({ behavior: "smooth" })}>Ver todas ↗</button></div><div className="recommendation-card"><div className="rec-number">01</div><div><span className="card-label">● RECOMENDADA PARA VOCÊ</span><h3>{activeBeach.name}</h3><p>{activeBeach.area}</p><div className="reasons"><span>↗ vento favorável</span><span>◒ período consistente</span><span>◌ maré boa</span></div></div><div className="score"><b>{activeBeach.score}</b><span>/ 100</span><small>índice Ondai</small></div><button className={`save ${saved ? "saved" : ""}`} onClick={() => setSaved(!saved)} aria-label="Salvar praia">{saved ? "♥" : "♡"}</button></div></section>
    <section className="workspace" id="mapa"><div className="card map-card"><div className="card-head"><div><span className="kicker">MAPA DE SESSÕES</span><h2>Praias por perto</h2></div><button className="filter">Filtrar　≡</button></div><div className="map"><div className="coast" /><span className="map-label l1">Stella Maris</span><span className="map-label l2">Praia do Flamengo</span><span className="map-label l3">Itapuã</span><span className="map-label l4">Jaguaribe</span>{beaches.map((beach, index) => <button key={beach.id} className={`marker m${index} ${activeBeach.id === beach.id ? "selected" : ""}`} style={{ "--marker": beach.color } as React.CSSProperties} onClick={() => setActiveBeach(beach)}>{beach.score}</button>)}</div><div className="legend"><span><i className="green" /> Boa para agora</span><span><i className="yellow" /> Regular</span><span><i className="coral" /> Para iniciantes</span></div></div><div className="card beach-card"><div className="card-head"><div><span className="kicker">CONDIÇÕES</span><h2>Agora em Salvador</h2></div><span className="live">● ao vivo</span></div><div className="beach-list">{beaches.map((beach) => <button className={`beach-row ${activeBeach.id === beach.id ? "chosen" : ""}`} key={beach.id} onClick={() => setActiveBeach(beach)}><i style={{ background: beach.color }} /><span className="beach-info"><b>{beach.name}</b><small>{beach.score >= 80 ? "Melhor opção" : beach.score >= 75 ? "Boa agora" : beach.id === "jaguaribe" ? "Para iniciantes" : "Regular"}</small></span><span className="metrics"><b>{beach.wave}</b><small>{beach.period} · {liveWind && activeBeach.id === beach.id ? liveWind : beach.wind.split("·")[1]}</small></span><span className="arrow">↗</span></button>)}</div><button className="outline-button" onClick={() => document.getElementById("relatos")?.scrollIntoView({ behavior: "smooth" })}>Abrir mapa completo　↗</button></div></section>
    <section className="insights"><div className="card chart-card"><div className="card-head"><div><span className="kicker">{activeBeach.name.toUpperCase()} · PRÓXIMAS 12H</span><h2>O mar se movimenta</h2></div><span className="source">Open-Meteo · {apiState}</span></div><div className="tabs">{tabs.map((tab) => <button className={activeTab === tab ? "active" : ""} key={tab} onClick={() => setActiveTab(tab)}>{tab}</button>)}</div><div className="chart"><div className="axis"><span>2,0</span><span>1,0</span><span>0,0</span></div><svg viewBox="0 0 576 110" preserveAspectRatio="none" aria-label={`Gráfico de ${activeTab}`}><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#74d7c9" stopOpacity=".3" /><stop offset="100%" stopColor="#74d7c9" stopOpacity="0" /></linearGradient></defs><path d={`${chart} L576 110 L0 110Z`} fill="url(#fill)" /><path d={chart} fill="none" stroke="#74d7c9" strokeWidth="3" vectorEffect="non-scaling-stroke" /></svg><div className="hours"><span>agora</span><span>12h</span><span>18h</span><span>00h</span><span>06h</span></div></div></div><div className="card tide-card"><span className="kicker">MARÉ DE HOJE</span><div className="tide-title"><h2>Subindo devagar</h2><span className="moon">◔</span></div><div className="tide-bar"><span /><em>agora</em></div><div className="tide-extremes"><div><small>BAIXA</small><b>0,2 m</b><span>05:42</span></div><div><small>ALTA</small><b>1,9 m</b><span>12:18</span></div><div><small>BAIXA</small><b>0,4 m</b><span>18:47</span></div></div><div className="source-note">Fonte: DHN / Marinha do Brasil ↗</div></div></section>
    <section className="reports" id="relatos"><div className="section-heading"><div><span className="kicker">DA COMUNIDADE · AGORA</span><h2>O que os surfistas estão vendo</h2></div><button className="view-all">Ver todos ↗</button></div><div className="report-grid"><article className="report"><div><b>Stella Maris</b><span>há 18 min</span></div><p>“Entrou uma linha boa no outside. Vento segurando e pouca gente na água.”</p><footer><i>M</i><span><b>Marina S.</b><small>Intermediário · <em>foto verificada</em></small></span><label>♡ 12</label></footer></article><article className="report"><div><b>Praia do Flamengo</b><span>há 42 min</span></div><p>“Mais cheio perto do canal, mas ainda tem espaço para remar. Onda divertida.”</p><footer><i className="warm">C</i><span><b>Caio R.</b><small>Avançado · <em>confirmado</em></small></span><label>♡ 8</label></footer></article><article className="report report-cta"><strong>＋</strong><h3>Você está no mar?</h3><p>Compartilhe uma leitura rápida e ajude a comunidade.</p><button className="primary-button">Enviar relato ↗</button></article></div></section>
    <section className="collab"><div><span className="kicker">PLANO COLABORADOR · EM BREVE</span><h2>Mais mar. Menos ruído.</h2><p>Alertas personalizados, histórico completo e uma experiência sem anúncios.</p></div><div className="price"><b>R$ 4,90</b><span>/ mês</span><small>fortaleça o movimento do surf</small></div><button>Conhecer o plano ↗</button></section>
    <footer className="site-footer" id="perfil"><div><strong><span className="brand-mark">◜</span>ondai</strong><small>O mar para quem vive o surf.</small></div><nav><a href="#inicio">Início</a><a href="#mapa">Mapa</a><a href="#relatos">Relatos</a><a href="#perfil">Perfil</a></nav><aside>ANUNCIE AQUI<br /><small>fortaleça o movimento do surf</small></aside></footer>
  </main>;
}
